

GET http://localhost:4000/api/groups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyLCJ1c2VybmFtZSI6Im1lcmVzYSIsInJvbGUiOiJ1c2VyIiwiaWF0IjoxNzU5NTUyOTg0LCJleHAiOjE3NTk2MzkzODR9.kKMBof2aEa_tyi6hJPGt1AskSaqRid1jY8cAM8V3uac
