POST http://localhost:4000/api/auth/login
Content-Type: application/json

{
  "email": "admin@gmail.com",
  "password": "admin"
}



eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoyMiwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1OTU2MzM0MiwiZXhwIjoxNzU5NjQ5NzQyfQ.ZATxU1oWe97xDP1St-2vn0az8J02_7giWCNIS7YC9J8